# Site settings
title: the uncarved blog
email: martin.adam.stoffel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog with some thoughts.
baseurl: /mastoffel.github.io
url:  # the base hostname & protocol for your site
twitter_username: 
github_username:  mastoffel

# Pagination
paginate: 15
paginate_path: "/mastoffel.github.io/page:num/"

# Build settings
markdown: kramdown

collections:
 photography:
    output: true
    permalink: /photography/:path/
 poetry:
    output: true
    permalink: /poetry/:path/
    
# Gems
gems: [jekyll-paginate]

 


