# Site settings
title: Weiwuwei
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/mastoffel.github.io" # the subpath of your site, e.g. /blog/
url: "http://mastoffel.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: mastoffel

# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md
